//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleMiner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleMiner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleMiner.
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ethWallet.
        /// </summary>
        internal static string EthCreateWalletLink {
            get {
                return ResourceManager.GetString("EthCreateWalletLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EthPool.
        /// </summary>
        internal static string EthPool {
            get {
                return ResourceManager.GetString("EthPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EthWallet.
        /// </summary>
        internal static string EthWallet {
            get {
                return ResourceManager.GetString("EthWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker.
        /// </summary>
        internal static string EthWorker {
            get {
                return ResourceManager.GetString("EthWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide details.
        /// </summary>
        internal static string HideDetailsButton {
            get {
                return ResourceManager.GetString("HideDetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoMiningLogo {
            get {
                object obj = ResourceManager.GetObject("IcoMiningLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to simpleminer@gmail.com.
        /// </summary>
        internal static string MailTo {
            get {
                return ResourceManager.GetString("MailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MiningLogo {
            get {
                object obj = ResourceManager.GetObject("MiningLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_error {
            get {
                object obj = ResourceManager.GetObject("s_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_settings {
            get {
                object obj = ResourceManager.GetObject("s_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_start {
            get {
                object obj = ResourceManager.GetObject("s_start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_stop {
            get {
                object obj = ResourceManager.GetObject("s_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        internal static string ShowDetailsButton {
            get {
                return ResourceManager.GetString("ShowDetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string tabAbout {
            get {
                return ResourceManager.GetString("tabAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethereum.
        /// </summary>
        internal static string tabEthereum {
            get {
                return ResourceManager.GetString("tabEthereum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string tabOptions {
            get {
                return ResourceManager.GetString("tabOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended parameters.
        /// </summary>
        internal static string ttConfigButton {
            get {
                return ResourceManager.GetString("ttConfigButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to close error dialog.
        /// </summary>
        internal static string ttErrorClose {
            get {
                return ResourceManager.GetString("ttErrorClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to show additional details.
        /// </summary>
        internal static string ttErrorDetails {
            get {
                return ResourceManager.GetString("ttErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool address for Ethereum mining.
        /// </summary>
        internal static string ttEthPool {
            get {
                return ResourceManager.GetString("ttEthPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address of your Ethereum wallet.
        /// </summary>
        internal static string ttEthWallet {
            get {
                return ResourceManager.GetString("ttEthWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker name.
        /// </summary>
        internal static string ttEthWorker {
            get {
                return ResourceManager.GetString("ttEthWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press for start mining.
        /// </summary>
        internal static string ttStartButton {
            get {
                return ResourceManager.GetString("ttStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press fro stop mining.
        /// </summary>
        internal static string ttStopButton {
            get {
                return ResourceManager.GetString("ttStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.google.com.
        /// </summary>
        internal static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
    }
}
